// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://igtadatnittnvllhijsj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlndGFkYXRuaXR0bnZsbGhpanNqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk0MzQyNjUsImV4cCI6MjA2NTAxMDI2NX0.JnsI2mM7lKOU1w7-CZHcTm2O0oi-XCIeL0zrvVMWqjA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);